"""Loading saved IMD observation records and making the base-rate table (unfrozen, KTD9).

Records are loaded by vintage name, so a provisional and a final copy of the
same day never mix. ``base_rates`` renders ``ledger/mandi-wheat/base-rates.md``
from committed files only: the same files always give the same text.
"""

import hashlib
import math
import statistics
import sys
from datetime import date
from pathlib import Path

import numpy as np

from khetru_evidence import bands, obs_core, semantics

LEDGER = "mandi-wheat"
BASE_RATES_PATH = "base-rates.md"
DEV_BUNDLE_DIR = "bundles/dev"
THRESHOLDS_MM = (2.0, 5.0, 10.0, 20.0)
SEASON_MONTHS = (10, 11)


def vintages(ledger_root: Path) -> list[str]:
    """Every vintage with a saved record, by name."""
    paths = (ledger_root / obs_core.OBSERVATIONS_DIR).glob("imd-*.json.gz")
    return sorted({"-".join(p.name.split("-")[1:3]) for p in paths})


def record_files(ledger_root: Path, vintage: str) -> list[Path]:
    return sorted((ledger_root / obs_core.OBSERVATIONS_DIR).glob(f"imd-{vintage}-*.json.gz"))


def load(ledger_root: Path, vintage: str) -> obs_core.Daily:
    """Every saved day of one vintage."""
    files = record_files(ledger_root, vintage)
    if not files:
        raise obs_core.ObservationError(f"no saved records of vintage {vintage}")
    return obs_core.daily(obs_core.decode_record(path.read_bytes()) for path in files)


def files_digest(files: list[Path]) -> str:
    """One SHA-256 over the names and hashes of ``files``, to name a set of records."""
    lines = [f"{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.name}\n" for p in sorted(files)]
    return hashlib.sha256("".join(lines).encode()).hexdigest()


def load_band_map(ledger_root: Path) -> bands.BandMap:
    return bands.decode((ledger_root / bands.BAND_MAP_PATH).read_bytes())


def full_years(series: obs_core.Daily) -> list[int]:
    """Years with every date of October and November in ``series``."""
    have = set(series.dates)
    years = sorted({d.year for d in have})
    return [y for y in years
            if all(d in have for d in obs_core.run_dates(date(y, 10, 1), 61))]


def missing_cells(series: obs_core.Daily, band_map: bands.BandMap, months=SEASON_MONTHS) -> tuple[int, int, int]:
    """(cell-days with no value, cell-days, days with any missing) over the map's cells in ``months``."""
    rows = [series.lats.index(c.lat) for c in band_map.cells]
    cols = [series.lons.index(c.lon) for c in band_map.cells]
    days = [i for i, d in enumerate(series.dates) if d.month in months]
    gone = np.isnan(series.values[days][:, rows, cols])
    return int(gone.sum()), gone.size, int(gone.any(axis=1).sum())


def _windows(sem: semantics.Semantics, year: int) -> list[tuple[date, ...]]:
    return [obs_core.imd_dates(semantics.schedule(sem, issue)) for issue in semantics.issue_dates(sem, year)]


def _pct(part: int, whole: int) -> str:
    return f"{100 * part / whole:.1f}%" if whole else "n/a"


def _mm(threshold: float) -> str:
    return f"{threshold:g} mm"


def base_rates(ledger_root: Path, vintage: str, provisional: str | None = None) -> str:
    """The base-rate table as Markdown, from the saved records of the final ``vintage``.

    ``provisional`` names a real-time vintage to count missing cells in and to
    set beside the final values where both hold a day.
    """
    bundle = ledger_root / DEV_BUNDLE_DIR
    sem = semantics.load(bundle / "bundle.toml")
    rules = obs_core.load_rules(bundle / "observations.toml")
    band_map = load_band_map(ledger_root)
    series = load(ledger_root, vintage)
    years = [y for y in full_years(series) if y >= rules.climatology_first_year]
    cutoff = f"{rules.sowing_cutoff[1]} {date(2000, rules.sowing_cutoff[0], 1):%b}"
    issue = semantics.issue_dates(sem, years[0])[0]
    lead = (obs_core.imd_dates(semantics.schedule(sem, issue))[0] - issue).days

    out = [
        "# Mandi wheat base rates from IMD observed rainfall", "",
        "Generated by `evidence observe base-rates`; do not edit. Every figure comes from the",
        "committed files named below, with the development rule values. The owner chooses the",
        "bundle v1 values at U8. No forecast enters this table.", "",
        "## Inputs", "",
        f"- Observations: IMD 0.25° gridded daily rainfall, vintage `{vintage}`,",
        f"  {len(record_files(ledger_root, vintage))} files under `observations/`,",
        f"  set digest `{files_digest(record_files(ledger_root, vintage))}`.",
        f"- Band map: `{bands.BAND_MAP_PATH}`, SHA-256",
        f"  `{hashlib.sha256((ledger_root / bands.BAND_MAP_PATH).read_bytes()).hexdigest()}`.",
        f"- Seasons: {years[0]} to {years[-1]} ({len(years)}).",
        f"- Issue dates: each Monday from {sem.season_start[1]} Oct to {sem.season_end[1]} Nov;",
        f"  the observed window is the {sem.rain_days} IMD dates starting {lead} days after it",
        "  (IMD's date D is the 24 hours ending 08:30 IST on D).",
        f"- Coverage share {rules.coverage_share:g}; wet day {_mm(rules.wet_day_mm)}; dry-day gap "
        f"{rules.dry_day_gap_days} days;",
        f"  climatology ±{rules.climatology_half_window_days} days with pseudo-count "
        f"{rules.climatology_pseudo_count:g}; sowing cutoff {cutoff}.", "",
    ]

    for verdict_band in band_map.verdict_bands:
        band = obs_core.band_daily(series, band_map, verdict_band, rules.coverage_share)
        out += _band_tables(band, verdict_band, years, sem, rules, cutoff)

    out += ["## Missing cell values, October and November", "",
            "Cell-days are counted over the band map's cells.", "",
            "| Vintage | Days | Cell-days | Missing cell-days | Days with a missing cell |",
            "|---|---|---|---|---|"]
    for name in filter(None, (vintage, provisional)):
        one = series if name == vintage else load(ledger_root, name)
        gone, size, days = missing_cells(one, band_map)
        out.append(f"| `{name}` | {size // len(band_map.cells)} | {size} | {gone} | {days} |")
    out.append("")
    if provisional:
        out += _provisional_table(series, load(ledger_root, provisional), band_map, rules)
    return "\n".join(out)


def _band_tables(band, verdict_band, years, sem, rules, cutoff) -> list[str]:
    days = sem.rain_days
    per_season: dict[int, list[str]] = {y: [] for y in years}
    summary, before, clim = [], [], []
    for threshold in THRESHOLDS_MM:
        held = judged = unverifiable = positive = negative = seasons_held = 0
        cut_held = cut_judged = cut_seasons = 0
        probabilities = []
        for year in years:
            windows = _windows(sem, year)
            results = [obs_core.outcome(obs_core.window_total(band, w), threshold) for w in windows]
            pos, neg = obs_core.episode_counts(band, windows, threshold, rules.wet_day_mm,
                                               rules.dry_day_gap_days)
            n_held = results.count(obs_core.HELD)
            held += n_held
            unverifiable += results.count(obs_core.UNVERIFIABLE)
            judged += len(results) - results.count(obs_core.UNVERIFIABLE)
            positive += pos
            negative += neg
            seasons_held += n_held > 0
            per_season[year].append(f"{n_held}/{len(results)} ({pos}+, {neg}−)")

            last = date(year, *rules.sowing_cutoff)
            cut = [obs_core.rain_before(band, w[0], last, days, threshold) for w in windows]
            cut_held += cut.count(obs_core.HELD)
            cut_judged += len(cut) - cut.count(obs_core.UNVERIFIABLE)
            cut_seasons += obs_core.HELD in cut

            others = [y for y in years if y != year]
            probabilities += [
                obs_core.climatology(
                    band, w[0], years=others, days=days, threshold_mm=threshold,
                    half_window_days=rules.climatology_half_window_days,
                    pseudo_count=rules.climatology_pseudo_count,
                ).probability for w in windows
            ]
        summary.append(
            f"| {_mm(threshold)} | {judged} | {held} | {_pct(held, judged)} | {positive} | {negative} "
            f"| {seasons_held} of {len(years)} | {unverifiable} |"
        )
        before.append(
            f"| {_mm(threshold)} | {cut_judged} | {cut_held} | {_pct(cut_held, cut_judged)} "
            f"| {cut_seasons} of {len(years)} |"
        )
        clim.append(
            f"| {_mm(threshold)} | {len(probabilities)} | {min(probabilities):.3f} "
            f"| {statistics.median(probabilities):.3f} | {max(probabilities):.3f} |"
        )

    names = " | ".join(_mm(t) for t in THRESHOLDS_MM)
    out = [
        f"## Verdict band `{verdict_band}`", "",
        f"### Rain in the {days}-day window", "",
        "One window per issue date. An episode count is of independent episodes: held windows",
        "fed by the same rain episode are one positive episode, and a run of windows in a row",
        "that did not hold is one negative episode.", "",
        "| Threshold | Windows | Held | Base rate | Positive episodes | Negative episodes "
        "| Seasons with a held window | Unverifiable |",
        "|---|---|---|---|---|---|---|---|", *summary, "",
        f"### Next rain before the sowing cutoff ({cutoff})", "",
        f"Held when some {days} dates in a row, from the window's first date to the cutoff, reach",
        "the threshold. One value per issue date; values in one season overlap heavily.", "",
        "| Threshold | Issue dates | Held | Base rate | Seasons with a held date |",
        "|---|---|---|---|---|", *before, "",
        "### Leave-one-season-out climatology", "",
        f"The probability climatology gives each window of the {days}-day event, from every other",
        "season. Smallest, median and largest over all windows.", "",
        "| Threshold | Windows | Smallest | Median | Largest |",
        "|---|---|---|---|---|", *clim, "",
        "### By season", "",
        f"Held windows out of windows, then positive (+) and negative (−) episodes, for the {days}-day event.", "",
        f"| Season | {names} |",
        "|---|" + "---|" * len(THRESHOLDS_MM),
        *(f"| {year} | {' | '.join(cells)} |" for year, cells in per_season.items()), "",
    ]
    return out


def _provisional_table(final, provisional, band_map, rules) -> list[str]:
    out = ["## Real-time against final values", "",
           f"Band-mean daily rainfall on the dates both `{provisional.vintage}` and `{final.vintage}` hold.", "",
           "| Verdict band | Dates | Wet in final | Wet in real-time | Wet in both "
           "| Mean absolute difference | Largest difference |",
           "|---|---|---|---|---|---|---|"]
    for verdict_band in band_map.verdict_bands:
        a = obs_core.band_daily(final, band_map, verdict_band, rules.coverage_share)
        b = obs_core.band_daily(provisional, band_map, verdict_band, rules.coverage_share)
        pairs = [(a[d], b[d]) for d in sorted(set(a) & set(b))
                 if not math.isnan(a[d]) and not math.isnan(b[d])]
        if not pairs:
            out.append(f"| `{verdict_band}` | 0 | | | | | |")
            continue
        wet = rules.wet_day_mm
        diffs = [abs(x - y) for x, y in pairs]
        out.append(
            f"| `{verdict_band}` | {len(pairs)} | {sum(x >= wet for x, _ in pairs)} "
            f"| {sum(y >= wet for _, y in pairs)} | {sum(x >= wet and y >= wet for x, y in pairs)} "
            f"| {math.fsum(diffs) / len(diffs):.2f} mm | {max(diffs):.2f} mm |"
        )
    return [*out, ""]


def write_base_rates(*, repo: Path, vintage: str, provisional: str | None, check: bool) -> int:
    """Write the table, or with ``check`` exit 1 unless the committed one matches."""
    ledger_root = repo / "ledger" / LEDGER
    text = base_rates(ledger_root, vintage, provisional)
    path = ledger_root / BASE_RATES_PATH
    if check:
        if path.exists() and path.read_text(encoding="utf-8") == text:
            print(f"reproduced {path.relative_to(repo)}")
            return 0
        print(f"{path.relative_to(repo)} differs from the table the committed files give", file=sys.stderr)
        return 1
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path.relative_to(repo)}")
    return 0
